name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Debug - List package.json dependencies
      run: cat package.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Debug - Check installed packages
      run: npm list --depth=0
    
    - name: Install missing dependencies
      run: npm install --no-save jest typescript-eslint cypress @typescript-eslint/eslint-plugin @typescript-eslint/parser
    
    - name: Install Cypress binary
      run: npx cypress install
    
    - name: Run affected tasks
      env:
        NODE_ENV: production
      run: npx nx affected --verbose -t lint test build e2e

